<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mtm_fertighauswelt_integration"
 *
 * Auto generated by Extension Builder 2020-06-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Fertighauswelt Integration',
    'description' => 'Diese Extension frägt Fertighäuser von der Fertighauswelt API ab.
Mehrere Darstellungen möglich: 
Häuser-Slider, Häuserliste, Hausdetail Ansicht, Anbieter-Slider, Anbieterliste, Anbieterdetail Ansicht, Geländeplan Ansicht & Merklistenseite + Widget',
    'category' => 'plugin',
    'author' => 'Nico Storto',
    'author_email' => 'storto@matoma.de',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
